name: Deploy Crowdstrike Pages
run-name: Deploying 🚀
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # 👇 这里指定了你的网站根目录是 crowdstrike 文件夹
          path: './crowdstrike'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
